
/**
* ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sobota, 2 września 2017 00:41:10 CEST
*/

public interface ServerInterfaceOperations 
{
  void setResources (int cores);
  void submit (String[] urls, int tasks, int parallelTasks, org.omg.CORBA.IntHolder userID);
  void done (int taskID);
  void cancel (int userID);
} // interface ServerInterfaceOperations
