
/**
* TaskInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sobota, 2 września 2017 00:41:10 CEST
*/

public interface TaskInterfaceOperations 
{
  void start (int taskID);
} // interface TaskInterfaceOperations
