
/**
* TaskInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sobota, 2 września 2017 00:41:10 CEST
*/

public interface TaskInterface extends TaskInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TaskInterface
