
/**
* TaskInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sobota, 2 września 2017 00:41:10 CEST
*/

public final class TaskInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public TaskInterface value = null;

  public TaskInterfaceHolder ()
  {
  }

  public TaskInterfaceHolder (TaskInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TaskInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TaskInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TaskInterfaceHelper.type ();
  }

}
